baseURL = "https://example.com"
languageCode = "en-in"
title = "Jughead"
copyright = "Â© Ananth Bhaskararaman"
enableGitInfo = true

# Code highlighting
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Site parameters
[params]
# Set to light or dark to force either theme.
# Leave unset for automatic theme detection and a toggle in the header.
# colourScheme = "light"
attribution = true    # show theme attribution in the footer
subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/ananthb/jughead)"

description = "Demo site for Jughead, a minimal and clean blog theme for Hugo."

# If enableGitInfo is true and this is set, a link to the commit will be shown in the footer.
github_repo = "ananthb/jughead"  # Site GitHub repository

# Follow setup instructions at https://utteranc.es.
utterances = "ananthb/jughead"  # Utterances GitHub repository for comments

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ananthb/jughead"
[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/me/"
[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/ananth/"
[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/ananth-bhaskararaman-2b4227316"

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
